export const arrayOfRandomPrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "An abstract landscape with pastel colors",
  "An image of a futuristic cityscape at night",
  "A close-up of a red rose",
  "An image of a serene mountain lake",
  "A surreal dreamscape with floating islands",
  "An image of a bustling street market in a medieval city",
  "A detailed portrait of a mythical dragon",
  "An image of a colorful jungle with exotic wildlife",
  "An underwater scene with vibrant coral and fish",
  "An image of a space shuttle launching into orbit",
  "Abstract image combining geometric shapes, colors, and textures.",
  "Futuristic cityscape.",
  "Realistic alien landscape.",
  "Imaginary creature with unique features.",
  "Magical forest.",
  "Robot in an urban environment.",
  "Steampunk-inspired machine.",
  "Post-apocalyptic world.",
  "Surreal image blending reality and fantasy.",
  "Surreal landscape combining natural and man-made elements.",
  "An underwater city.",
  "A futuristic space station.",
  "A deserted island.",
  "A lush jungle.",
  "A deserted street.",
  "A robot factory.",
  "A haunted house.",
  "A neon-lit cityscape.",
  "A celestial landscape.",
  "An abandoned castle.",
  "A space-age utopia.",
  "A barren wasteland.",
  "A cyberpunk-inspired city.",
  "A haunted forest.",
  "A crystal-filled cave.",
  "A mysterious temple.",
  "A futuristic vehicle.",
  "A robotic animal.",
  "A fantasy creature.",
  "A colorful landscape.",
  "An alien planet.",
  "A supernatural being.",
  "A steampunk-inspired machine.",
  "A magical forest.",
  "A post-apocalyptic world.",
  "A surreal image.",
  "A surreal landscape.",
  "A celestial body.",
  "A ghostly apparition.",
  "A robotic arm.",
  "An alien landscape.",
  "A mystical creature.",
  "A futuristic city.",
  "A virtual world.",
  "A starry night sky.",
  "A robotic sentinel.",
  "A robotic warrior.",
  "A robotic armada.",
  "An alien spacecraft.",
  "A mysterious portal.",
  "A hidden temple.",
  "A cyberpunk-inspired cityscape.",
  "A barren wasteland.",
  "An alien world.",
  //continue using different artistic styles at the end of the sentence, miss the duplicates and dont start with "Generate an image of"
  "A vibrant landscape in pastel colors.",
  "A surreal scene in neon hues.",
  "A dark fantasy painting.",
  "A dreamy landscape in watercolor.",
  "A colorful abstract painting.",
  "A minimalist black and white image.",
  "A surreal image in bright colors.",
  "A futuristic cityscape in pastel shades.",
  "A vibrant and surreal scene in neon hues.",
  "A realistic alien landscape in muted tones.",
  "An imaginary creature with unique features in vibrant colors.",
  "A magical forest in pastel shades.",
  "A robot in an urban environment in muted tones.",
  "A steampunk-inspired machine in bright colors.",
  "A post-apocalyptic world in pastel shades.",
  "A surreal image blending reality and fantasy in neon hues.",
  "A surreal landscape combining natural and man-made elements in muted tones.",
  "An underwater city in vibrant colors.",
  "A futuristic space station in pastel shades.",
  "A deserted island in neon hues.",
  "A lush jungle in muted tones.",
  "A deserted street in vibrant colors.",
  "A robot factory in pastel shades.",
  "A haunted house in neon hues.",
  "A neon-lit cityscape in muted tones.",
  "A celestial landscape in vibrant colors.",
  "An abandoned castle in pastel shades.",
  "A space-age utopia in neon hues.",
  "A barren wasteland in muted tones.",
  "A cyberpunk-inspired city in vibrant colors.",
  "A haunted forest in pastel shades.",
  "A crystal-filled cave in neon hues.",
  "A mysterious temple in muted tones.",
  "A futuristic vehicle in vibrant colors.",
  "A robotic animal in pastel shades.",
  "A fantasy creature in neon hues.",
  "A colorful landscape in muted tones.",
  "An alien planet in vibrant colors.",
  "A supernatural being in pastel shades.",
  "A steampunk-inspired machine in neon hues.",
  "A magical forest in muted tones",
  "A post-apocalyptic world in vibrant colors.",
  "A surreal image blending reality and fantasy in pastel shades.",
  "A surreal landscape combining natural and man-made elements in neon hues.",
  "An underwater city in muted tones.",
  "A futuristic space station in vibrant colors.",
  "A deserted island in pastel shades.",
  "A lush jungle in neon hues.",
  "A deserted street in muted tones.",
  "A robot factory in vibrant colors.",
  "A haunted house in pastel shades.",
  "A neon-lit cityscape in neon hues.",
  "A celestial landscape in muted tones.",
  "An abandoned castle in vibrant colors.",
  "A space-age utopia in pastel shades.",
  "A barren wasteland in neon hues.",
  "A cyberpunk-inspired city in muted tones.",
  "A haunted forest in vibrant colors.",
  "A crystal-filled cave in pastel shades.",
  "A mysterious temple in neon hues.",
  "A futuristic vehicle in muted tones.",
  "A robotic animal in vibrant colors.",
  "A fantasy creature in pastel shades.",
  "A colorful landscape in neon hues.",
  "An alien planet in muted tones.",
  "A supernatural being in vibrant colors.",
  "A steampunk-inspired machine in pastel shades.",
  "A magical forest in neon hues.",
  "A post-apocalyptic world in muted tones.",
  "A surreal image blending reality and fantasy in vibrant colors.",
  "A surreal landscape combining natural and man-made elements in pastel shades.",
  "A meadow of wildflowers in neon hues.",
  "A tranquil lake in muted tones.",
  "A mountain range in vibrant colors.",
  "A dense forest in pastel shades.",
  "A rocky beach in neon hues.",
  "A desert oasis in muted tones.",
  "A waterfall in vibrant colors.",
  "A snow-covered landscape in pastel shades.",
  "A starry night sky in neon hues.",
  "A pasture of grazing animals in muted tones.",
  "A grassland of rolling hills in vibrant colors.",
  "A woodland of towering trees in pastel shades.",
  "A meadow of mushrooms in neon hues.",
  "A marsh of reeds in muted tones.",
  "A field of wildflowers in vibrant colors.",
  "A river of flowing water in pastel shades.",
  "A lake of glowing stars in neon hues.",
  "A canyon of rocky cliffs in muted tones.",
  "A valley of rugged terrain in vibrant colors.",
  "A canyon of lush foliage in pastel shades.",
  "A meadow of butterflies in neon hues.",
  "A cave of stalagmites in muted tones.",
  "A beach of coral reefs in vibrant colors.",
  "A forest of glowing mushrooms in pastel shades.",
  "A pond of colorful fish in neon hues.",
  "A mountain of snow-capped peaks in muted tones.",
  "A plain of rolling hills in vibrant colors.",
  "A desert of sand dunes in pastel shades.",
  "A surrealist image of a meadow of wildflowers painted in Salvador Dali style.",
  "A realistic image of a tranquil lake painted in Edward Hopper style.",
  "An impressionist painting of a mountain range in Claude Monet style.",
  "An art nouveau image of a dense forest in Alphonse Mucha style.",
  "A modern art image of a rocky beach in Wassily Kandinsky style.",
  "An abstract painting of a desert oasis in Piet Mondrian style.",
  "A cubist image of a waterfall in Pablo Picasso style.",
  "A cartoon image of a snow-covered landscape in Charles Schulz style.",
  "A brutalist image of a starry night sky in Zaha Hadid style.",
  "A minimalist image of a pasture of grazing animals in Kazimir Malevich style.",
  "A conceptual art image of a grassland of rolling hills in Yoko Ono style.",
  "A surrealist image of a woodland of towering trees in Max Ernst style.",
  "A realistic image of a meadow of mushrooms in Andrew Wyeth style.",
  "An impressionist painting of a marsh of reeds in Pierre-Auguste Renoir style.",
  "An art nouveau image of a field of wildflowers in Alphonse Mucha style.",
  "A modern art image of a river of flowing water in Wassily Kandinsky style.",
  "An abstract painting of a lake of glowing stars in Piet Mondrian style.",
  "A cubist image of a canyon of rocky cliffs in Pablo Picasso style.",
  "A cartoon image of a valley of rugged terrain in Charles Schulz style.",
  "A brutalist image of a canyon of lush foliage in Zaha Hadid style.",
  "A minimalist image of a meadow of butterflies in Kazimir Malevich style.",
  "A conceptual art image of a cave of stalagmites in Yoko Ono style.",
  "A surrealist image of a beach of coral reefs in Max Ernst style.",
  "A realistic image of a forest of glowing mushrooms in Andrew Wyeth style.",
  "An impressionist painting of a pond of colorful fish in Pierre-Auguste Renoir style.",
  "An art nouveau image of a mountain of snow-capped peaks in Alphonse Mucha style.",
  "A modern art image of a plain of rolling hills in Wassily Kandinsky style.",
  "An abstract painting of a desert of sand dunes in Piet Mondrian style.",
];
